import { useEffect, useState } from "react";
import { Code, Play, RotateCcw, ArrowLeft, CheckCircle } from "lucide-react";
import { dracula } from "@uiw/codemirror-theme-dracula";
import { javascript } from "@codemirror/lang-javascript";
import CodeMirror from "@uiw/react-codemirror";

interface QuestionData {
  problem: string;
  example: string;
  constraints: string;
  note: string | null;
}

const App = () => {
  const [aiReady, setAiReady] = useState(false);
  const [code, setCode] = useState(
    "function solution() {\n  // Your code here \n}"
  );
  const [questionData, setQuestionData] = useState<QuestionData | null>(null);
  const [loading, setLoading] = useState(false);
  const [solved, setSolved] = useState(false);
  const [feedback, setFeedback] = useState("");
  const [warning, setWarning] = useState("");
  const [difficulty, setDifficulty] = useState("");

  useEffect(() => {
    const checkReady = setInterval(() => {
      if (window.puter?.ai?.chat) {
        setAiReady(true);
        clearInterval(checkReady);
      }
    }, 300);
    return () => clearInterval(checkReady);
  }, []);

  const handleDifficultySelect = (level: string) => {
    setDifficulty(level);
    if (warning) setWarning("");
  };
  const generateQuestion = async () => {
    const validLevels = ["Easy", "Medium", "Hard"];
    if (!validLevels.includes(difficulty)) {
      setWarning(
        "⚠ Please select a difficulty level before generate a question"
      );
      return;
    }
    setLoading(true);
    setCode("function solution() {\n  // Your code here \n}");
    setQuestionData(null);
    setFeedback("");
    setWarning("");
    setSolved(false);
    try {
      const res = await window.puter?.ai?.chat(`
        Generate a ${difficulty} level coding interview question like on leetcode.Return ONLY valid JSON with this Structure:{
        'problem':'string',
        'example':'string',
        'constraints':'string',
        'note':'string or empty if none'
        }
        `);
      const reply = typeof res === "string" ? res : res?.message?.content || "";
      const parsed = JSON.parse(reply);
      setQuestionData(parsed);
    } catch (error: unknown) {
      if (error instanceof Error) setFeedback(`❌ Error ${error.message}`);
    }
    setLoading(false);
  };
  const checkSolution = async () => {
    if (!code.trim()) return;
    setLoading(true);
    try {
      const res = await window.puter?.ai?.chat(`
        You are a helpful interview coach.
        The question is: "${questionData?.problem}".
        Here is the candidate's solution":\n${code}
        if Correct,say:'✔ Correct! Well Done',
        If Wrong,give hints but dont reveal the full answer.
        `);
      const reply = typeof res === "string" ? res : res?.message?.content || "";
      if (reply.includes("✔ Correct")) setSolved(true);
      setFeedback(reply);
    } catch (error: unknown) {
      if (error instanceof Error) setFeedback(`❌ Error ${error.message}`);
    }
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-sky-900 via-slate-950 to-emerald-900 flex flex-col items-center justify-center p-6 gap-10">
      <h1 className="text-6xl sm:text-8xl bg-gradient-to-r from-emerald-400 via-sky-400 to-blue-500 bg-clip-text text-transparent font-bold text-center">
        AI Interview Coach
      </h1>
      <div className="w-full max-w-7xl flex flex-col justify-center items-center">
        {!questionData ? (
          <div className="w-full max-w-md p-10  bg-gray-900/80 backdrop-blur-md border border-gray-700 rounded-3xl shadow-lg shadow-sky-600 hover:shadow-2xl hover:shadow-sky-400 transition duration-300 text-center ">
            <Code className="mx-auto w-24 h-24 text-cyan-400 mb-6" />
            <h2 className="mb-4 text-3xl text-white font-semibold ">
              Ready to Practice
            </h2>
            <p className="text-slate-300 mb-8 leading-relaxed">
              Solve coding interview questions generated by AI , get hints, and
              improve your skills.
            </p>
            <div className="mb-8">
              <p className="text-sky-400 text-lg text-left font-semibold mb-4">
                Select Difficulty :
              </p>
              <div className="flex justify-center gap-3 flex-wrap sm:flex-nowrap">
                {["Easy", "Medium", "Hard"].map((level) => (
                  <button
                    key={level}
                    onClick={() => handleDifficultySelect(level)}
                    className={`px-6 py-3 rounded-full font-semibold transition-colors duration-200 cursor-pointer ${
                      difficulty === level
                        ? "bg-blue-500 text-white shadow-md "
                        : "bg-gray-700 text-gray-300 hover:bg-gray-600"
                    } `}
                  >
                    {level}
                  </button>
                ))}
              </div>
            </div>
            {warning && (
              <p className="text-red-500 font-semibold mb-4">{warning}</p>
            )}
            <button
              className="w-full px-10 py-4 bg-gradient-to-r from-sky-400 to-emerald-400 hover:from-sky-500 hover:to-emerald-500 rounded-3xl shadow-lg transitio duration-300 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer text-white text-lg font-semibold"
              disabled={loading || !aiReady}
              onClick={generateQuestion}
            >
              {loading ? "Generating..." : "Generate"}
            </button>
          </div>
        ) : (
          <div className="space-y-6 w-full">
            <div className="grid lg:grid-cols-2 gap-6">
              <div className="bg-gradient-to-br from-blue-950/40 to-sky-950/50 backdrop-blur-sm border border-indigo-400/30 rounded-2xl shadow-2xl p-8 space-y-4">
                <div>
                  <h3 className="text-lg font-semibold text-emerald-400 mb-1">
                    Problem
                  </h3>
                  <p className="text-gray-200">{questionData.problem}</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-emerald-400 mb-1">
                    Example
                  </h3>
                  <pre className="bg-black/30 p-3 text-gray-200 whitespace-pre-wrap rounded">
                    {questionData.example}
                  </pre>
                </div>
                <div className="text-lg font-semibold text-emerald-400 mb-1">
                  <h3>Constraints</h3>
                  <ul className="list-disc list-inside text-gray-200">
                    {questionData.constraints.split("\n").map((line, idx) => (
                      <li key={idx}>{line}</li>
                    ))}
                  </ul>
                </div>
                {questionData.note && (
                  <div>
                    <h3 className="text-lg font-semibold text-emerald-400 mb-1">
                      Note
                    </h3>
                    <p className="text-gray-200">{questionData.note}</p>
                  </div>
                )}
              </div>
              <div className="bg-gray-800/60 border border-gray-700/50 rounded-2xl shadow-2xl overflow-hidden">
                <div className="bg-gray-900/90 px-4 py-3 border-b border-gray-700/50 flex items-center gap-3">
                  <Code className="w-5 h-5 text-emerald-500" />
                  <h3 className="text-lg text-white font-semibold">
                    Solution:
                  </h3>
                </div>
                <CodeMirror
                  value={code}
                  height="550px"
                  extensions={[javascript({ jsx: true })]}
                  theme={dracula}
                  onChange={(val) => setCode(val)}
                />
              </div>
            </div>
            <div className="flex gap-6 lg:gap-10 justify-center items-center flex-col lg:flex-row">
              <div className="flex  gap-3 flex-wrap justify-center items-center">
                <button
                  onClick={checkSolution}
                  disabled={loading || !aiReady || !code.trim()}
                  className="px-6 py-3 bg-gradient-to-r from-blue-500 to-emerald-500 hover:opacity-80
                  disabled:opacity-50 text-white font-semibold rounded-2xl transition-all duration-300 flex justify-center items-center gap-2 cursor-pointer"
                >
                  <Play className="w-5 h-5" />
                  {loading ? "Checking..." : "Check Solution"}
                </button>
                <button
                  onClick={generateQuestion}
                  disabled={loading || !aiReady || solved}
                  className="px-6 py-3 bg-gradient-to-r from-purple-500 to-rose-500 
                  hover:opacity-80 disabled:opacity-50 text-white font-semibold rounded-2xl transition-all duration-300 flex justify-center items-center gap-2 cursor-pointer"
                >
                  <RotateCcw className="w-5 h-5" />
                  {loading ? "Generating..." : "New Question"}
                </button>
                <button
                  onClick={() => {
                    setQuestionData(null);
                    setCode("function solution() {\n  // Your code here \n}");
                    setFeedback("");
                    setWarning("");
                    setLoading(false);
                    setSolved(false);
                    setDifficulty("");
                  }}
                  disabled={loading}
                  className="px-6 py-3 bg-gradient-to-r from-red-500 to-amber-500 
                  hover:opacity-80 disabled:opacity-50 text-white font-semibold rounded-2xl transition-all duration-300 flex justify-center items-center gap-2 cursor-pointer"
                >
                  <ArrowLeft className="w-5 h-5" />
                  Go Back
                </button>
              </div>
              <div className="flex justify-center items-center gap-3 flex-wrap sm:flex-nowrap">
                <p className="text-slate-300 font-semibold mb-0">
                  Difficulty :
                </p>
                {["Easy", "Medium", "Hard"].map((level) => (
                  <button
                    key={level}
                    onClick={() => handleDifficultySelect(level)}
                    className={`px-6 py-3 rounded-full font-semibold transition-colors duration-200 cursor-pointer ${
                      difficulty === level
                        ? "bg-blue-500 text-white shadow-md "
                        : "bg-gray-700 text-gray-300 hover:bg-gray-600"
                    } `}
                  >
                    {level}
                  </button>
                ))}
              </div>
            </div>
            {feedback && (
              <div
                className={`rounded-3xl p-6 shadow-2xl backdrop-blur-sm ${
                  feedback.includes("✔")
                    ? "bg-green-900/40 border border-green-500/30"
                    : feedback.includes("❌")
                    ? "bg-red-900/40 border border-red-500/30"
                    : "bg-gray-800/60 border border-gray-700/50"
                }`}
              >
                <div className="flex items-start gap-4">
                  <CheckCircle
                    className={`w-6 h-6 ${
                      feedback.includes("✔")
                        ? "text-green-400"
                        : feedback.includes("❌")
                        ? "text-red-400"
                        : "text-blue-400"
                    }`}
                  />
                  <div className="flex-1 text-gray-200 whitespace-pre-wrap leading-relaxed">
                    {feedback}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default App;
